### ISSUE TITLE
settimezone function bug

### ISSUE THREAD

**Issue by senorsmile** [helmuthdu/aui#226]
The line in sharedfuncs:
local _subzones=(`timedatectl list-timezones | grep ${_zones} | sed 's/^.*\///'`)

renders that function inoperable, always doing a grep for africa instead of what you actually select.  
The line needs to change to the following to work:
local _subzones=(`timedatectl list-timezones | grep ${ZONE} | sed 's/^.*\///'`)

**Comment by helmuthdu** [comment]
Fixed, Thx! :)
