### ISSUE TITLE
FIFO installation on VMWare = No DHCP on Ethernet

### ISSUE THREAD

**Issue by julianxhokaxhiu** [helmuthdu/aui#230]
Hi,

today I was installing Arch Linux (latest ISO available on the website) and I tryed your installation script. I found that the FIFO script is missing the dhcpcd enable action.

The reason is contained in this line ( https://github.com/helmuthdu/aui/blob/master/fifo#L460 ), I don't know if by just fixing it from this
```bash
local WIRED_DEV=`ip link | grep enp | awk '{print $2}'| sed 's/://' | sed '1!d'`
```
to this
```bash
local WIRED_DEV=`ip link | grep eno | awk '{print $2}'| sed 's/://' | sed '1!d'`
```
is ok, but actually that makes it to work because of the output of `ip link` that is

```bash
[root@archiso ~]# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eno16777736: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:57:25:b2 brd ff:ff:ff:ff:ff:ff
```
any clue on how to fix this without breaking maybe other conditions that aren't met? (Virutalbox, Physical installation, etc.)

Thanks in advice for this super easy script :)

**Comment by helmuthdu** [comment]
For now i can't see what is wrong, have to wait until i came home to test it...

**Comment by julianxhokaxhiu** [comment]
The interface `enp` doesn't seem to exist, at least in VMWare (Ethernet connection), while the interface `eno` does. So renaming `enp` to `eno` on that line fix the detection.

But I'm not sure if this is related only to VMWare or even to Physical installations as well.

**Comment by helmuthdu** [comment]
Bad bad, i mad a correction... Everything should work now :+1:

**Comment by julianxhokaxhiu** [comment]
Thank you! :D +1 for your script, yay!

**Comment by mibbio** [comment]
It's not only VMWare. Systemd 197 introduced a new scheme for network device names.
http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

**Comment by julianxhokaxhiu** [comment]
Hello,

it's me again :) It seems that using the latest Arch Image ( 3 March 2016 ) over VMWare Workstation Player 12.1 this line ( https://github.com/helmuthdu/aui/blob/master/fifo#L503 ) is failing again on the detection.

This round the Ethernet adapter is called `ens32`:
```zsh
root@archiso ~ # ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:1d:8c:0b brd ff:ff:ff:ff:ff:ff
```

Can you fix this please? :D
