### ISSUE TITLE
Installing from USB

### ISSUE THREAD

**Issue by RangerMauve** [helmuthdu/aui#239]
How would this be used in conjunction with [the usb flash installation](https://wiki.archlinux.org/index.php/USB_flash_installation_media) guide?

**Comment by phikal** [comment]
Just clone the project into `root`'s home directory and run it. Or am I getting you wrong?

**Comment by RangerMauve** [comment]
I was just wondering if anything special had to be done. But I guess I was overthinking things. Thanks!

**Comment by djfj74** [comment]
This is stupid @RangerMauve

**Comment by RangerMauve** [comment]
Thank you Derrick. That was very necessary and you are very mature.

**Comment by djfj74** [comment]
LOL

**Comment by f3bruary** [comment]
For an offline system you can also just copy the repo to the root of the usb stick. Then you can find it somewhere in /run I believe. Just "find /run -name 'aui-master'" or whatever you named it.

**Comment by phikal** [comment]
@f3bruary If it's not found, use `fdisk -l` to list all your connected devices. It should probably be either `/dev/sdb` or `/dev/sdc`. Use `mount /dev/sdX /mnt` to attatch the device to `/mnt`, and when you cd into it, all folders should be there.
