### ISSUE TITLE
AUR helpers not installing

### ISSUE THREAD

**Issue by Pednick** [helmuthdu/aui#258]
AUR helpers not installing because of AUR move.

**Comment by Odel** [comment]
I changed line 458 of sharedfuncs to:
curl -o ${PKG}.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/${PKG}.tar.gz

Seemed to work alright after that, at least when selecting Yaourt, haven't tried the others.

**Comment by helmuthdu** [comment]
Could someone make a pull request? I only have time to try this probably at weekend.
