### ISSUE TITLE
UEFI dual boot windows 10 issue

### ISSUE THREAD

**Issue by ldtpht** [helmuthdu/aui#273]
the grub can't find the windows, when i use your script, it's ask me to format the efi partition, should i do it or not?

**Comment by luca020400** [comment]
os-prober handle windows partitions, and you must run it after first reboot . ( sudo os-prober )
You shouldn't format efi partition unless you have only archlinux on your HDD

I'll fix the fact that os-prober should be executed on post configuration

**Comment by ldtpht** [comment]
all solved. thank you so much!
